define numeric DEBUG = 1 ; // YES =1 NO = 0

// Family
define numeric F_INVISIBLE = 1 ;
define numeric F_VISIBLE1 = 2 ;
define numeric F_VISIBLE2 = 3 ;
define numeric F_CREATURE = 4 ;
// Genus
define numeric G_ZERO = 0 ;
define numeric G_SYSTEM = 1 ;
define numeric G_GUI = 2 ;
define numeric G_HAND = 1;
define numeric G_DOOR = 2;
define numeric G_SEED = 3;
define numeric G_GOODPLANT = 4;

// script
//0
define numeric S_POINTER = 0 ;
//1
define numeric S_SIMPLEMONITOR =10 ;
define numeric S_DUMMY = 12 ;
define numeric S_BACKTOASTART = 100;
define numeric S_MONITORBUTTON = 110;
define numeric S_INJECTBUTTON = 120;
define numeric S_LIGHT = 150;
define numeric S_HEAT = 151;
define numeric S_NUTRIENT = 152;
define numeric S_FOO = 1000;
define numeric S_SWITCH = 180;
//2

define numeric S_BUBBLE_HANDLING = 3;
define numeric S_BUBBLE_HANDLING2 = 9;
define numeric S_BUBBLE_HANDLING1 = 10;
define numeric S_ZSWICHER = 1000;
//3




//4
define numeric S_SIMPLEPLANT = 4;
define numeric S_SIMPLEPLANT2 = 6;

//define 
