define numeric DEBUG = 1 ; // YES =1 NO = 0

// Family
define numeric F_INVISIBLE = 1 ;
define numeric F_VISIBLE1 = 2 ;
define numeric F_VISIBLE2 = 3 ;
define numeric F_CREATURE = 4 ;
// Genus
define numeric G_ZERO = 0 ;
define numeric G_SYSTEM = 1 ;
define numeric G_GUI = 2 ;
define numeric G_MACHINERY = 3 ;
define numeric G_HAND = 1;
define numeric G_DOOR = 2;
define numeric G_SEED = 3;
define numeric G_GOODPLANT = 4;

define numeric G_FOOD =11;
define numeric G_GOOD_BUG =13;
define numeric G_NEST =17;

define numeric G_WEATHER =19;
define numeric G_TOY =21;
// script
//0
define numeric S_POINTER = 0 ;
//1
define numeric S_SIMPLEMONITOR =10 ;
define numeric S_GUI =5 ;
define numeric S_PROG =6;
define numeric S_BACKTOASTART = 100;
define numeric S_MONITORBUTTON = 110;
define numeric S_INJECTBUTTON = 120;
define numeric S_LIGHT = 150;
define numeric S_HEAT = 151;
define numeric S_NUTRIENT = 152;

define numeric S_SHOOTER = 170;
define numeric S_SHOOTERSEED = 171;
define numeric S_TREE = 172;
define numeric S_TREEFLOWER = 173;
define numeric S_TREEFRUIT = 174;
define numeric S_BUBBLEJET = 175;
define numeric S_BUBBLE = 176;
define numeric S_BALOON = 177;
define numeric S_BALL = 178;
define numeric S_SWITCH = 180;
define numeric S_WEATHERMONITOR = 190;
define numeric S_CLOUD = 191;
define numeric S_LCLOUD=192;
define numeric S_SUN=193;
define numeric S_RAIN=194;
define numeric S_HRAIN=195;
define numeric S_METEO = 250;
define numeric S_FAUNA = 251;
define numeric S_TEST2 = 252;
define numeric S_TEST1 = 253;
define numeric S_DUMMY = 254;
define numeric S_FOO = 1000;
//2
define numeric S_NEST = 20;
define numeric S_GRUB = 21;
define numeric S_LBUG = 22;
define numeric S_BUBBLE_HANDLING = 3;
define numeric S_BUBBLE_HANDLING2 = 9;
define numeric S_BUBBLE_HANDLING1 = 10;

//3
define numeric S_SIMPLEMACHINERY = 10;




//4
define numeric S_SIMPLEPLANT = 4;
define numeric S_SIMPLEPLANT2 = 6;

//define 
