/**


  program: !DEMO WORLD1
    ___________________________________________________________________________

    Version 0.1

    Copyright (C) 2008 august0815
     
    git://github.com/august0815/lifandi_demo1.git
 
 About : Licence
 ..........................................................................
 GNU
 
 
 */
/**
Files: DEMO Files

* Run with :  openc2e -d linkto/lifandi_demo
* You neet KaosLib.k and my lib2.k,classifer.k and mach.sh to compile the *.k files with kaos
* FIRST : The lib2.k must be put in the prelude folder of kaos and kaos has to be recompiled. 
* The !map.cos is the only file written in CAOS with help of the Creatures Map Editor ,with little modifications
* 
* 
*/
