/**


    Script: pre defined OVXX
    ___________________________________________________________________________

    Version 0.1

    Copyright (C) 2008 august0815
   * under GNU
 * -----------------------------------------------------------------------------
 * Used in all agents for same meaning
 * -----------------------------------------------------------------------------
 * ovar numeric stats[0];
 * ovar numeric age_of_agent[1];
 * ovar numeric energy[2];
 * ovar numeric stage_of_life[5];
 * ovar numeric gender[6];
 * ovar numeric cast[7];
 * ovar numeric x_heading[10];
 * ovar numeric y_heading[11];
 * ovar numeric vel1[12];
 * ovar numeric vel2[13];
 * ovar numeric vel3[14];
 * ovar numeric vel4[15];
 * ovar numeric current[16];
 * ovar agent targ1[17];
 * ovar agent targ2[18];
 * ovar numeric base0[30];
 * ovar numeric base1[31];
 * ovar numeric base2[32];
 * ovar numeric base3[33];
 * ovar numeric base4[34];
 * ovar numeric base5[35];
 * ovar numeric base6[36];;
 * ovar numeric wet[60];
 * ovar numeric bioenergy[61];
 * -----------------------------------------------------------------------------

 */

ovar numeric stats[0];
ovar numeric age_of_agent[1];
ovar numeric energy[2];
ovar numeric stage_of_life[5];
ovar numeric gender[6];
ovar numeric cast[7];
ovar numeric x_heading[10];
ovar numeric y_heading[11];
ovar numeric vel1[12];
ovar numeric vel2[13];
ovar numeric vel3[14];
ovar numeric vel4[15];
ovar numeric current[16];
ovar agent targ1[17];
ovar agent targ2[18];
ovar numeric base0[30];
ovar numeric base1[31];
ovar numeric base2[32];
ovar numeric base3[33];
ovar numeric base4[34];
ovar numeric base5[35];
ovar numeric base6[36];
ovar numeric base7[37];
ovar numeric base8[38];
ovar numeric base9[39];

ovar numeric wet[60];
ovar numeric bioenergy[61];
